/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { ClientGrantAllowAnyOrganizationEnum } from "../../../../types/ClientGrantAllowAnyOrganizationEnum.js";
import type { ClientGrantSubjectTypeEnum } from "../../../../types/ClientGrantSubjectTypeEnum.js";

/**
 * @example
 *     {}
 */
export interface ListClientGrantsRequestParameters {
    /** Optional Id from which to start selection. */
    from?: string;
    /** Number of results per page. Defaults to 50. */
    take?: number;
    /** Optional filter on audience. */
    audience?: string;
    /** Optional filter on client_id. */
    client_id?: string;
    /** Optional filter on allow_any_organization. */
    allow_any_organization?: ClientGrantAllowAnyOrganizationEnum;
    /** The type of application access the client grant allows. Use of this field is subject to the applicable Free Trial terms in Okta’s <a href="https://www.okta.com/legal/"> Master Subscription Agreement.</a> */
    subject_type?: ClientGrantSubjectTypeEnum;
}
