/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { GuardianFactorsProviderSmsProviderEnum } from "../../../../../../../../types/GuardianFactorsProviderSmsProviderEnum.js";

/**
 * @example
 *     {
 *         provider: "auth0"
 *     }
 */
export interface SetGuardianFactorsProviderSmsRequestContent {
    provider: GuardianFactorsProviderSmsProviderEnum;
}
