// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient";
import { Enrollments } from "../resources/enrollments/client/Client";
import { Factors } from "../resources/factors/client/Client";
import { Policies } from "../resources/policies/client/Client";

export declare namespace Guardian {
    export interface Options extends BaseClientOptions {}
}

export class Guardian {
    protected readonly _options: Guardian.Options;
    protected _enrollments: Enrollments | undefined;
    protected _factors: Factors | undefined;
    protected _policies: Policies | undefined;

    constructor(_options: Guardian.Options) {
        this._options = _options;
    }

    public get enrollments(): Enrollments {
        return (this._enrollments ??= new Enrollments(this._options));
    }

    public get factors(): Factors {
        return (this._factors ??= new Factors(this._options));
    }

    public get policies(): Policies {
        return (this._policies ??= new Policies(this._options));
    }
}
