version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:6.14.3-browsers
    environment:
          LANG: en_US.UTF-8
    steps:
      - checkout
      - run: 
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore-cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name: Check
          command: yarn check
      - run: 
          name: Tests
          command: yarn test:ci
      - run: 
          name: Generate Coverage
          command: yarn test:coverage

workflows:
  version: 2
  build-test-report:
    jobs:
      - build-and-test