version: 2.1
orbs:
  ship: auth0/ship@0.3.1
  codecov: codecov/codecov@3
jobs:
  build-and-test:
    parameters:
      node-version:
        type: string
        default: "16.18"
    docker:
      - image: cimg/node:<< parameters.node-version >>
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: ESLint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Tests
          command: yarn test:ci
      - when:
          condition:
            equal: [ "16.18", << parameters.node-version >> ]
          steps:
            - codecov/upload
workflows:
  build-test-report:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              node-version: ["16.18", "18.12"]
      - ship/node-publish:
          pkg-manager: yarn
          requires:
            - build-and-test
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master
