version: 2.1
orbs:
  ship: auth0/ship@0.7.8
  codecov: codecov/codecov@3
jobs:
  build-and-test:
    parameters:
      node-version:
        type: string
        default: "18.17"
    docker:
      - image: cimg/node:<< parameters.node-version >>
    resource_class: xlarge
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - ship/node-install-packages
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Tests
          command: npm run test:ci
      - when:
          condition:
            equal: [ "18.17", << parameters.node-version >> ]
          steps:
            - codecov/upload
workflows:
  build-test-report:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              node-version: ["18.17", "20.3"]
      - ship/node-publish:
          publish-command: npm run build && npm publish --tag beta
          requires:
            - build-and-test
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - beta
