version: 2.1
orbs:
  ship: auth0/ship@0.2.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - ship/node-install-packages:
          pkg-manager: yarn
      - run:
          name: Check
          command: yarn check
      - run:
          name: Tests
          command: yarn test:ci
      - run:
          name: Generate Coverage
          command: yarn test:coverage
workflows:
  build-test-report:
    jobs:
      - build-and-test
      - ship/node-publish:
          pkg-manager: yarn
          requires:
            - build-and-test
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master
