imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /roles/{id}/permissions
      method: GET
      auth: true
      docs: >
        Retrieve detailed list (name, description, resource server) of
        permissions granted by a specified user role.
      pagination:
        offset: $request.page
        results: $response.permissions
      source:
        openapi: ../api.json
      path-parameters:
        id:
          type: string
          docs: ID of the role to list granted permissions.
      display-name: Get permissions granted by role
      request:
        name: ListRolePermissionsRequestParameters
        query-parameters:
          per_page:
            type: optional<integer>
            default: 50
            docs: Number of results per page. Defaults to 50.
          page:
            type: optional<integer>
            docs: Page index of the results to return. First page is 0.
          include_totals:
            type: optional<boolean>
            default: true
            docs: >-
              Return results inside an object that contains the total result
              count (true) or as a direct array of results (false, default).
      response:
        docs: Role permissions successfully retrieved.
        type: root.ListRolePermissionsOffsetPaginatedResponseContent
        status-code: 200
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.NotFoundError
        - root.TooManyRequestsError
      examples:
        - path-parameters:
            id: id
          response:
            body:
              start: 1.1
              limit: 1.1
              total: 1.1
              permissions:
                - resource_server_identifier: resource_server_identifier
                  permission_name: permission_name
                  resource_server_name: resource_server_name
                  description: description
    add:
      path: /roles/{id}/permissions
      method: POST
      auth: true
      docs: >
        Add one or more <a
        href="https://auth0.com/docs/manage-users/access-control/configure-core-rbac/manage-permissions">permissions</a>
        to a specified user role.
      source:
        openapi: ../api.json
      path-parameters:
        id:
          type: string
          docs: ID of the role to add permissions to.
      display-name: Associate permissions with a role
      request:
        name: AddRolePermissionsRequestContent
        body:
          properties:
            permissions:
              docs: array of resource_server_identifier, permission_name pairs.
              type: list<root.PermissionRequestPayload>
        content-type: application/json
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.TooManyRequestsError
      examples:
        - path-parameters:
            id: id
          request:
            permissions:
              - resource_server_identifier: resource_server_identifier
                permission_name: permission_name
    delete:
      path: /roles/{id}/permissions
      method: DELETE
      auth: true
      docs: >
        Remove one or more <a
        href="https://auth0.com/docs/manage-users/access-control/configure-core-rbac/manage-permissions">permissions</a>
        from a specified user role.
      source:
        openapi: ../api.json
      path-parameters:
        id:
          type: string
          docs: ID of the role to remove permissions from.
      display-name: Remove permissions from a role
      request:
        name: DeleteRolePermissionsRequestContent
        body:
          properties:
            permissions:
              docs: array of resource_server_identifier, permission_name pairs.
              type: list<root.PermissionRequestPayload>
        content-type: application/json
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
        - root.ForbiddenError
        - root.TooManyRequestsError
      examples:
        - path-parameters:
            id: id
          request:
            permissions:
              - resource_server_identifier: resource_server_identifier
                permission_name: permission_name
  source:
    openapi: ../api.json
