/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool.js";
import { ManagementClient } from "../../../Client.js";
import * as Management from "../../../api/index.js";

describe("UsersExports", () => {
    test("create (9bd53ff1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "status",
            type: "type",
            created_at: "created_at",
            id: "id",
            connection_id: "connection_id",
            format: "json",
            limit: 1,
            fields: [{ name: "name", export_as: "export_as" }],
        };
        server
            .mockEndpoint()
            .post("/jobs/users-exports")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.usersExports.create();
        expect(response).toEqual({
            status: "status",
            type: "type",
            created_at: "created_at",
            id: "id",
            connection_id: "connection_id",
            format: "json",
            limit: 1,
            fields: [
                {
                    name: "name",
                    export_as: "export_as",
                },
            ],
        });
    });

    test("create (f557ff6e)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection_id: undefined, format: undefined, limit: undefined, fields: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/jobs/users-exports")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.usersExports.create({
                connection_id: undefined,
                format: undefined,
                limit: undefined,
                fields: undefined,
            });
        }).rejects.toThrow(
            new Management.BadRequestError({
                key: "value",
            }),
        );
    });

    test("create (37bbbaf6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection_id: undefined, format: undefined, limit: undefined, fields: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/jobs/users-exports")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.usersExports.create({
                connection_id: undefined,
                format: undefined,
                limit: undefined,
                fields: undefined,
            });
        }).rejects.toThrow(
            new Management.UnauthorizedError({
                key: "value",
            }),
        );
    });

    test("create (4b5391fa)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection_id: undefined, format: undefined, limit: undefined, fields: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/jobs/users-exports")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.usersExports.create({
                connection_id: undefined,
                format: undefined,
                limit: undefined,
                fields: undefined,
            });
        }).rejects.toThrow(
            new Management.ForbiddenError({
                key: "value",
            }),
        );
    });

    test("create (2f18f096)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { connection_id: undefined, format: undefined, limit: undefined, fields: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/jobs/users-exports")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.usersExports.create({
                connection_id: undefined,
                format: undefined,
                limit: undefined,
                fields: undefined,
            });
        }).rejects.toThrow(
            new Management.TooManyRequestsError({
                key: "value",
            }),
        );
    });
});
