/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import { Verification } from "../resources/verification/client/Client.js";

export declare namespace VerifiableCredentials {
    export interface Options {
        environment?: core.Supplier<environments.ManagementEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }
}

export class VerifiableCredentials {
    protected readonly _options: VerifiableCredentials.Options;
    protected _verification: Verification | undefined;

    constructor(_options: VerifiableCredentials.Options) {
        this._options = _options;
    }

    public get verification(): Verification {
        return (this._verification ??= new Verification(this._options));
    }
}
