/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { ManagementClient } from "../../Client.js";

describe("EventStreams", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                subscriptions: [{}],
                destination: {
                    type: "webhook",
                    configuration: {
                        webhook_endpoint: "webhook_endpoint",
                        webhook_authorization: { method: "basic", username: "username" },
                    },
                },
                status: "enabled",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        ];
        server.mockEndpoint().get("/event-streams").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.eventStreams.list();
        expect(response).toEqual([
            {
                id: "id",
                name: "name",
                subscriptions: [{}],
                destination: {
                    type: "webhook",
                    configuration: {
                        webhook_endpoint: "webhook_endpoint",
                        webhook_authorization: {
                            method: "basic",
                            username: "username",
                        },
                    },
                },
                status: "enabled",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        ]);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: { method: "basic", username: "username" },
                },
            },
        };
        const rawResponseBody = {
            id: "id",
            name: "name",
            subscriptions: [{ event_type: "event_type" }],
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: { method: "basic", username: "username" },
                },
            },
            status: "enabled",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/event-streams")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventStreams.create({
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: {
                        method: "basic",
                        username: "username",
                    },
                },
            },
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            subscriptions: [
                {
                    event_type: "event_type",
                },
            ],
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: {
                        method: "basic",
                        username: "username",
                    },
                },
            },
            status: "enabled",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            subscriptions: [{ event_type: "event_type" }],
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: { method: "basic", username: "username" },
                },
            },
            status: "enabled",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server.mockEndpoint().get("/event-streams/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.eventStreams.get("id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            subscriptions: [
                {
                    event_type: "event_type",
                },
            ],
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: {
                        method: "basic",
                        username: "username",
                    },
                },
            },
            status: "enabled",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/event-streams/id").respondWith().statusCode(200).build();

        const response = await client.eventStreams.delete("id");
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            subscriptions: [{ event_type: "event_type" }],
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: { method: "basic", username: "username" },
                },
            },
            status: "enabled",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .patch("/event-streams/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventStreams.update("id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            subscriptions: [
                {
                    event_type: "event_type",
                },
            ],
            destination: {
                type: "webhook",
                configuration: {
                    webhook_endpoint: "webhook_endpoint",
                    webhook_authorization: {
                        method: "basic",
                        username: "username",
                    },
                },
            },
            status: "enabled",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("getStats", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            window: {
                date_from: "2024-01-15T09:30:00Z",
                date_to: "2024-01-15T09:30:00Z",
                bucket_interval: { scale_factor: 1 },
            },
            buckets: ["2024-01-15T09:30:00Z"],
            metrics: [{ name: "name", window_total: 1.1, type: "type", data: [1.1] }],
        };
        server
            .mockEndpoint()
            .get("/event-streams/id/stats")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventStreams.getStats("id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            window: {
                date_from: "2024-01-15T09:30:00Z",
                date_to: "2024-01-15T09:30:00Z",
                bucket_interval: {
                    scale_factor: 1,
                },
            },
            buckets: ["2024-01-15T09:30:00Z"],
            metrics: [
                {
                    name: "name",
                    window_total: 1.1,
                    type: "type",
                    data: [1.1],
                },
            ],
        });
    });

    test("test", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { event_type: "user.created" };
        const rawResponseBody = {
            id: "id",
            event_stream_id: "event_stream_id",
            status: "failed",
            event_type: "user.created",
            attempts: [{ status: "failed", timestamp: "2024-01-15T09:30:00Z", error_message: "error_message" }],
            event: {
                id: "id",
                source: "source",
                specversion: "specversion",
                type: "type",
                time: "2024-01-15T09:30:00Z",
                data: "data",
            },
        };
        server
            .mockEndpoint()
            .post("/event-streams/id/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eventStreams.test("id", {
            event_type: "user.created",
        });
        expect(response).toEqual({
            id: "id",
            event_stream_id: "event_stream_id",
            status: "failed",
            event_type: "user.created",
            attempts: [
                {
                    status: "failed",
                    timestamp: "2024-01-15T09:30:00Z",
                    error_message: "error_message",
                },
            ],
            event: {
                id: "id",
                source: "source",
                specversion: "specversion",
                type: "type",
                time: "2024-01-15T09:30:00Z",
                data: "data",
            },
        });
    });
});
