/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../mock-server/MockServerPool.js";
import { ManagementClient } from "../../../../Client.js";

describe("Bindings", () => {
    test("updateMany", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            bindings: [
                {
                    id: "id",
                    trigger_id: "trigger_id",
                    display_name: "display_name",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server
            .mockEndpoint()
            .patch("/actions/triggers/triggerId/bindings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.actions.triggers.bindings.updateMany("triggerId");
        expect(response).toEqual({
            bindings: [
                {
                    id: "id",
                    trigger_id: "trigger_id",
                    display_name: "display_name",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        });
    });
});
