/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListOrganizationConnectionsRequestParameters {
    /**
     * Page index of the results to return. First page is 0.
     */
    page?: number;
    /**
     * Number of results per page. Defaults to 50.
     */
    per_page?: number;
    /**
     * Return results inside an object that contains the total result count (true) or as a direct array of results (false, default).
     */
    include_totals?: boolean;
}
