// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient";
import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import { Connections } from "../resources/connections/client/Client";

export declare namespace Vault {
    export interface Options extends BaseClientOptions {}
}

export class Vault {
    protected readonly _options: Vault.Options;
    protected _connections: Connections | undefined;

    constructor(_options: Vault.Options) {
        this._options = _options;
    }

    public get connections(): Connections {
        return (this._connections ??= new Connections(this._options));
    }
}
