/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateResourceServerRequestContent {
    /** Friendly name for this resource server. Can not contain `<` or `>` characters. */
    name?: string;
    /** List of permissions (scopes) that this API uses. */
    scopes?: Management.ResourceServerScope[];
    signing_alg?: Management.SigningAlgorithmEnum;
    /** Secret used to sign tokens when using symmetric algorithms (HS256). */
    signing_secret?: string;
    /** Whether to skip user consent for applications flagged as first party (true) or not (false). */
    skip_consent_for_verifiable_first_party_clients?: boolean;
    /** Whether refresh tokens can be issued for this API (true) or not (false). */
    allow_offline_access?: boolean;
    /** Expiration value (in seconds) for access tokens issued for this API from the token endpoint. */
    token_lifetime?: number;
    token_dialect?: Management.ResourceServerTokenDialectSchemaEnum;
    /** Whether authorization policies are enforced (true) or not enforced (false). */
    enforce_policies?: boolean;
    token_encryption?: Management.ResourceServerTokenEncryption;
    consent_policy?: Management.ResourceServerConsentPolicyEnum | undefined;
    authorization_details?: unknown[];
    proof_of_possession?: Management.ResourceServerProofOfPossession;
}
