// This file was auto-generated by Fern from our API Definition.

import * as Management from "../../../api/index";
import { ManagementClient } from "../../../Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SettingsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { enabled: true };
        server
            .mockEndpoint()
            .get("/risk-assessments/settings")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.riskAssessments.settings.get();
        expect(response).toEqual({
            enabled: true,
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/risk-assessments/settings")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.get();
        }).rejects.toThrow(Management.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/risk-assessments/settings")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.get();
        }).rejects.toThrow(Management.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/risk-assessments/settings")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.get();
        }).rejects.toThrow(Management.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/risk-assessments/settings")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.get();
        }).rejects.toThrow(Management.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = { enabled: true };
        server
            .mockEndpoint()
            .patch("/risk-assessments/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.riskAssessments.settings.update({
            enabled: true,
        });
        expect(response).toEqual({
            enabled: true,
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/risk-assessments/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.update({
                enabled: true,
            });
        }).rejects.toThrow(Management.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/risk-assessments/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.update({
                enabled: true,
            });
        }).rejects.toThrow(Management.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/risk-assessments/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.update({
                enabled: true,
            });
        }).rejects.toThrow(Management.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/risk-assessments/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.update({
                enabled: true,
            });
        }).rejects.toThrow(Management.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/risk-assessments/settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.riskAssessments.settings.update({
                enabled: true,
            });
        }).rejects.toThrow(Management.TooManyRequestsError);
    });
});
