/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { TestActionPayload } from "../../../../types/TestActionPayload.js";

/**
 * @example
 *     {
 *         payload: {
 *             "key": "value"
 *         }
 *     }
 */
export interface TestActionRequestContent {
    payload: TestActionPayload;
}
