/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool.js";
import { ManagementClient } from "../../../Client.js";

describe("FederatedConnectionsTokensets", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                connection: "connection",
                scope: "scope",
                expires_at: "2024-01-15T09:30:00Z",
                issued_at: "2024-01-15T09:30:00Z",
                last_used_at: "2024-01-15T09:30:00Z",
            },
        ];
        server
            .mockEndpoint()
            .get("/users/id/federated-connections-tokensets")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.federatedConnectionsTokensets.list("id");
        expect(response).toEqual([
            {
                id: "id",
                connection: "connection",
                scope: "scope",
                expires_at: "2024-01-15T09:30:00Z",
                issued_at: "2024-01-15T09:30:00Z",
                last_used_at: "2024-01-15T09:30:00Z",
            },
        ]);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/users/id/federated-connections-tokensets/tokenset_id")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.users.federatedConnectionsTokensets.delete("id", "tokenset_id");
        expect(response).toEqual(undefined);
    });
});
