// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../mock-server/MockServerPool";
import { ManagementClient } from "../../../Client";
import * as Management from "../../../api/index";

describe("IdentitiesClient", () => {
    test("link (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = [
            {
                connection: "connection",
                user_id: "user_id",
                provider: "provider",
                profileData: {
                    email: "email",
                    email_verified: true,
                    name: "name",
                    username: "username",
                    given_name: "given_name",
                    phone_number: "phone_number",
                    phone_verified: true,
                    family_name: "family_name",
                },
                isSocial: true,
                access_token: "access_token",
                access_token_secret: "access_token_secret",
                refresh_token: "refresh_token",
            },
        ];
        server
            .mockEndpoint()
            .post("/users/id/identities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.identities.link("id");
        expect(response).toEqual([
            {
                connection: "connection",
                user_id: "user_id",
                provider: "provider",
                profileData: {
                    email: "email",
                    email_verified: true,
                    name: "name",
                    username: "username",
                    given_name: "given_name",
                    phone_number: "phone_number",
                    phone_verified: true,
                    family_name: "family_name",
                },
                isSocial: true,
                access_token: "access_token",
                access_token_secret: "access_token_secret",
                refresh_token: "refresh_token",
            },
        ]);
    });

    test("link (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/users/id/identities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.link("id");
        }).rejects.toThrow(Management.BadRequestError);
    });

    test("link (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/users/id/identities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.link("id");
        }).rejects.toThrow(Management.UnauthorizedError);
    });

    test("link (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/users/id/identities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.link("id");
        }).rejects.toThrow(Management.ForbiddenError);
    });

    test("link (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/users/id/identities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.link("id");
        }).rejects.toThrow(Management.ConflictError);
    });

    test("link (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/users/id/identities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.link("id");
        }).rejects.toThrow(Management.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                connection: "connection",
                user_id: "user_id",
                provider: "provider",
                isSocial: true,
                access_token: "access_token",
                access_token_secret: "access_token_secret",
                refresh_token: "refresh_token",
                profileData: {
                    email: "email",
                    email_verified: true,
                    name: "name",
                    username: "username",
                    given_name: "given_name",
                    phone_number: "phone_number",
                    phone_verified: true,
                    family_name: "family_name",
                },
            },
        ];
        server
            .mockEndpoint()
            .delete("/users/id/identities/ad/user_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.identities.delete("id", "ad", "user_id");
        expect(response).toEqual([
            {
                connection: "connection",
                user_id: "user_id",
                provider: "provider",
                isSocial: true,
                access_token: "access_token",
                access_token_secret: "access_token_secret",
                refresh_token: "refresh_token",
                profileData: {
                    email: "email",
                    email_verified: true,
                    name: "name",
                    username: "username",
                    given_name: "given_name",
                    phone_number: "phone_number",
                    phone_verified: true,
                    family_name: "family_name",
                },
            },
        ]);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/users/id/identities/ad/user_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.delete("id", "ad", "user_id");
        }).rejects.toThrow(Management.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/users/id/identities/ad/user_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.delete("id", "ad", "user_id");
        }).rejects.toThrow(Management.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/users/id/identities/ad/user_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.delete("id", "ad", "user_id");
        }).rejects.toThrow(Management.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ManagementClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/users/id/identities/ad/user_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.identities.delete("id", "ad", "user_id");
        }).rejects.toThrow(Management.TooManyRequestsError);
    });
});
