/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Rendering mode to filter by
 */
export type AculRenderingModeEnum = "advanced" | "standard";
export const AculRenderingModeEnum = {
    Advanced: "advanced",
    Standard: "standard",
} as const;
