/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * Organizations array filter items
 */
export type AculOrganizationFilter =
    | Management.AculOrganizationFilterById
    | Management.AculOrganizationFilterByMetadata;
