/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Links style
 */
export type BrandingThemeFontLinksStyleEnum = "normal" | "underlined";
export const BrandingThemeFontLinksStyleEnum = {
    Normal: "normal",
    Underlined: "underlined",
} as const;
