// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index";

export interface BreachedPasswordDetectionPreUserRegistrationStage {
    /**
     * Action to take when a breached password is detected during a signup.
     *               Possible values: <code>block</code>, <code>admin_notification</code>.
     */
    shields?: Management.BreachedPasswordDetectionPreUserRegistrationShieldsEnum[];
}
