/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * Defines the default Organization ID and flows
 */
export interface ClientDefaultOrganization {
    /** The default Organization ID to be used */
    organization_id: string;
    /** The default Organization usage */
    flows: Management.ClientDefaultOrganizationFlowsEnum[];
}
