// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index.js";

/**
 * Response for connections with strategy=vkontakte
 */
export interface ConnectionResponseContentVkontakte extends Management.ConnectionRequestCommon {
    strategy: "vkontakte";
    options?: Management.ConnectionOptionsVkontakte;
    id?: Management.ConnectionId;
    name?: Management.ConnectionName;
}
