// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index";

/**
 * Options for enabling authentication methods.
 */
export interface ConnectionAuthenticationMethods {
    password?: Management.ConnectionPasswordAuthenticationMethod;
    passkey?: Management.ConnectionPasskeyAuthenticationMethod;
}
