// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index.js";

/**
 * Response for connections with strategy=paypal
 */
export interface ConnectionResponseContentPaypal extends Management.ConnectionRequestCommon {
    strategy: "paypal";
    options?: Management.ConnectionOptionsPaypal;
    id?: Management.ConnectionId;
    name?: Management.ConnectionName;
}
