// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index.js";

/**
 * Response for connections with strategy=baidu
 */
export interface ConnectionResponseContentBaidu extends Management.ConnectionRequestCommon {
    strategy: "baidu";
    options?: Management.ConnectionOptionsBaidu;
    id?: Management.ConnectionId;
    name?: Management.ConnectionName;
}
