// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index.js";

/**
 * Response for connections with strategy=apple
 */
export interface ConnectionResponseContentApple extends Management.ConnectionRequestCommon {
    strategy: "apple";
    options?: Management.ConnectionOptionsApple;
    id?: Management.ConnectionId;
    name?: Management.ConnectionName;
}
