// This file was auto-generated by Fern from our API Definition.

import type * as Management from "../index.js";

export type CreateFlowsVaultConnectionClearbit =
    | Management.CreateFlowsVaultConnectionClearbitApiKey
    | Management.CreateFlowsVaultConnectionClearbitUninitialized;
