// This file was auto-generated by Fern from our API Definition.

import type * as Management from "../index";

export interface CreateFlowsVaultConnectionStripeKeyPair {
    /** Flows Vault Connection name. */
    name: string;
    app_id: Management.FlowsVaultConnectionAppIdStripeEnum;
    setup: Management.FlowsVaultConnectioSetupStripeKeyPair;
}
