/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowAction } from "../types/FlowAction.js";

export interface CreateFlowResponseContent {
    id: string;
    name: string;
    actions?: FlowAction[];
    created_at: string;
    updated_at: string;
    executed_at?: string;
}
