/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { CreateFlowsVaultConnectionSlackWebhook } from "../types/CreateFlowsVaultConnectionSlackWebhook.js";
import type { CreateFlowsVaultConnectionSlackOauthCode } from "../types/CreateFlowsVaultConnectionSlackOauthCode.js";
import type { CreateFlowsVaultConnectionSlackUninitialized } from "../types/CreateFlowsVaultConnectionSlackUninitialized.js";

export type CreateFlowsVaultConnectionSlack =
    | CreateFlowsVaultConnectionSlackWebhook
    | CreateFlowsVaultConnectionSlackOauthCode
    | CreateFlowsVaultConnectionSlackUninitialized;
