/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { CreateFlowsVaultConnectionTwilioApiKey } from "../types/CreateFlowsVaultConnectionTwilioApiKey.js";
import type { CreateFlowsVaultConnectionTwilioUninitialized } from "../types/CreateFlowsVaultConnectionTwilioUninitialized.js";

export type CreateFlowsVaultConnectionTwilio =
    | CreateFlowsVaultConnectionTwilioApiKey
    | CreateFlowsVaultConnectionTwilioUninitialized;
