// This file was auto-generated by Fern from our API Definition.

import type * as Management from "../index.js";

export interface CreatePhoneTemplateResponseContent {
    id: string;
    channel?: string;
    customizable?: boolean;
    tenant?: string;
    content: Management.PhoneTemplateContent;
    type: Management.PhoneTemplateNotificationTypeEnum;
    /** Whether the template is enabled (false) or disabled (true). */
    disabled: boolean;
}
