// This file was auto-generated by Fern from our API Definition.

/** Type of the encryption key to be created. */
export const CreateEncryptionKeyType = {
    CustomerProvidedRootKey: "customer-provided-root-key",
    TenantEncryptionKey: "tenant-encryption-key",
} as const;
export type CreateEncryptionKeyType = (typeof CreateEncryptionKeyType)[keyof typeof CreateEncryptionKeyType] | string;
