/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreatedUserAuthenticationMethodTypeEnum = "phone" | "email" | "totp" | "webauthn-roaming" | "passkey";
export const CreatedUserAuthenticationMethodTypeEnum = {
    Phone: "phone",
    Email: "email",
    Totp: "totp",
    WebauthnRoaming: "webauthn-roaming",
    Passkey: "passkey",
} as const;
