/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { TokenQuotaClientCredentials } from "../types/TokenQuotaClientCredentials.js";

export interface CreateTokenQuota {
    client_credentials: TokenQuotaClientCredentials;
}
