// This file was auto-generated by Fern from our API Definition.

/** Custom domain provisioning type. Can be `auth0_managed_certs` or `self_managed_certs`. */
export const CustomDomainTypeEnum = {
    Auth0ManagedCerts: "auth0_managed_certs",
    SelfManagedCerts: "self_managed_certs",
} as const;
export type CustomDomainTypeEnum = (typeof CustomDomainTypeEnum)[keyof typeof CustomDomainTypeEnum];
