/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface EventStreamActionDestination {
    type: Management.EventStreamActionDestinationTypeEnum;
    configuration: Management.EventStreamActionConfiguration;
}
