/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionHttpSendRequestParamsPayloadObject } from "../types/FlowActionHttpSendRequestParamsPayloadObject.js";

export type FlowActionHttpSendRequestParamsPayload = string | unknown[] | FlowActionHttpSendRequestParamsPayloadObject;
