/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionFlowStoreVarsParamsVars } from "../types/FlowActionFlowStoreVarsParamsVars.js";

export interface FlowActionFlowStoreVarsParams {
    vars: FlowActionFlowStoreVarsParamsVars;
}
