// This file was auto-generated by Fern from our API Definition.

import type * as Management from "../index";

export interface FlowActionXmlParseXml {
    id: string;
    alias?: string;
    type: "XML";
    action: "PARSE_XML";
    allow_failure?: boolean;
    mask_output?: boolean;
    params: Management.FlowActionXmlParseXmlParams;
}
