/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionFlowMapValueParamsFallbackObject } from "../types/FlowActionFlowMapValueParamsFallbackObject.js";

export type FlowActionFlowMapValueParamsFallback =
    | string
    | number
    | FlowActionFlowMapValueParamsFallbackObject
    | unknown[];
