// This file was auto-generated by Fern from our API Definition.

export const FlowsVaultConnectioSetupJwtAlgorithmEnum = {
    Hs256: "HS256",
    Hs384: "HS384",
    Hs512: "HS512",
    Rs256: "RS256",
    Rs384: "RS384",
    Rs512: "RS512",
    Es256: "ES256",
    Es384: "ES384",
    Es512: "ES512",
    Ps256: "PS256",
    Ps384: "PS384",
    Ps512: "PS512",
} as const;
export type FlowsVaultConnectioSetupJwtAlgorithmEnum =
    (typeof FlowsVaultConnectioSetupJwtAlgorithmEnum)[keyof typeof FlowsVaultConnectioSetupJwtAlgorithmEnum];
