/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionSlackPostMessage } from "../types/FlowActionSlackPostMessage.js";

export type FlowActionSlack = FlowActionSlackPostMessage;
