/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionZapierTriggerWebhook } from "../types/FlowActionZapierTriggerWebhook.js";

export type FlowActionZapier = FlowActionZapierTriggerWebhook;
