/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FlowActionSalesforceSearchLeadsParams {
    connection_id: string;
    search_field: FlowActionSalesforceSearchLeadsParams.SearchField;
    search_value: string;
    lead_fields: string[];
}

export namespace FlowActionSalesforceSearchLeadsParams {
    export type SearchField = "email" | "name" | "phone" | "all";
    export const SearchField = {
        Email: "email",
        Name: "name",
        Phone: "phone",
        All: "all",
    } as const;
}
