// This file was auto-generated by Fern from our API Definition.

export type FlowActionHttpSendRequestParamsQueryParams = Record<
    string,
    (FlowActionHttpSendRequestParamsQueryParams.Value | null) | undefined
>;

export namespace FlowActionHttpSendRequestParamsQueryParams {
    export type Value = number | string;
}
