/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionJsonParseJsonParams } from "../types/FlowActionJsonParseJsonParams.js";

export interface FlowActionJsonParseJson {
    id: string;
    alias?: string;
    type: "JSON";
    action: "PARSE_JSON";
    allow_failure?: boolean;
    mask_output?: boolean;
    params: FlowActionJsonParseJsonParams;
}
