/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionSalesforceUpdateLeadParamsPayload } from "../types/FlowActionSalesforceUpdateLeadParamsPayload.js";

export interface FlowActionSalesforceUpdateLeadParams {
    connection_id: string;
    lead_id: string;
    payload?: FlowActionSalesforceUpdateLeadParamsPayload;
}
