/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export type FlowActionFlow =
    | Management.FlowActionFlowBooleanCondition
    | Management.FlowActionFlowDelayFlow
    | Management.FlowActionFlowDoNothing
    | Management.FlowActionFlowErrorMessage
    | Management.FlowActionFlowMapValue
    | Management.FlowActionFlowReturnJson
    | Management.FlowActionFlowStoreVars;
