/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FlowActionTelegramSendMessage } from "../types/FlowActionTelegramSendMessage.js";

export type FlowActionTelegram = FlowActionTelegramSendMessage;
