/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface FormBlockResendButton {
    id: string;
    category: Management.FormComponentCategoryBlockConst;
    type: Management.FormBlockTypeResendButtonConst;
    config: Management.FormBlockResendButtonConfig;
}
