/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FormFieldCardsConfigOption } from "../types/FormFieldCardsConfigOption.js";

export interface FormFieldCardsConfig {
    hide_labels?: boolean;
    multiple?: boolean;
    options?: FormFieldCardsConfigOption[];
}
