/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { FormComponentCategoryFieldConst } from "../types/FormComponentCategoryFieldConst.js";
import type { FormFieldTypeTelConst } from "../types/FormFieldTypeTelConst.js";
import type { FormFieldTelConfig } from "../types/FormFieldTelConfig.js";

export interface FormFieldTel {
    id: string;
    category: FormComponentCategoryFieldConst;
    type: FormFieldTypeTelConst;
    config?: FormFieldTelConfig;
    label?: string;
    hint?: string;
    required?: boolean;
    sensitive?: boolean;
}
