/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FormFieldChoiceConfig {
    multiple?: boolean;
    options?: FormFieldChoiceConfig.Options.Item[];
    allow_other?: FormFieldChoiceConfig.AllowOther;
}

export namespace FormFieldChoiceConfig {
    export type Options = Options.Item[];

    export namespace Options {
        export interface Item {
            value: string;
            label: string;
        }
    }

    export interface AllowOther {
        enabled?: boolean;
        label?: string;
        placeholder?: string;
    }
}
