/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormBlockImageConfigPositionEnum = "LEFT" | "CENTER" | "RIGHT";
export const FormBlockImageConfigPositionEnum = {
    Left: "LEFT",
    Center: "CENTER",
    Right: "RIGHT",
} as const;
