// This file was auto-generated by Fern from our API Definition.

export const GetFlowRequestParametersHydrateEnum = {
    FormCount: "form_count",
    Forms: "forms",
} as const;
export type GetFlowRequestParametersHydrateEnum =
    (typeof GetFlowRequestParametersHydrateEnum)[keyof typeof GetFlowRequestParametersHydrateEnum];
