/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GuardianFactorsProviderPushNotificationProviderDataEnum = "guardian" | "sns" | "direct";
export const GuardianFactorsProviderPushNotificationProviderDataEnum = {
    Guardian: "guardian",
    Sns: "sns",
    Direct: "direct",
} as const;
