/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { PermissionsResponsePayload } from "../types/PermissionsResponsePayload.js";

export interface ListRolePermissionsOffsetPaginatedResponseContent {
    start?: number;
    limit?: number;
    total?: number;
    permissions?: PermissionsResponsePayload[];
}
