/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Category group name
 */
export type LogStreamFilterGroupNameEnum =
    | "auth.ancillary.fail"
    | "auth.ancillary.success"
    | "auth.login.fail"
    | "auth.login.notification"
    | "auth.login.success"
    | "auth.logout.fail"
    | "auth.logout.success"
    | "auth.signup.fail"
    | "auth.signup.success"
    | "auth.silent_auth.fail"
    | "auth.silent_auth.success"
    | "auth.token_exchange.fail"
    | "auth.token_exchange.success"
    | "management.fail"
    | "management.success"
    | "scim.event"
    | "system.notification"
    | "user.fail"
    | "user.notification"
    | "user.success"
    | "actions"
    | "other";
export const LogStreamFilterGroupNameEnum = {
    AuthAncillaryFail: "auth.ancillary.fail",
    AuthAncillarySuccess: "auth.ancillary.success",
    AuthLoginFail: "auth.login.fail",
    AuthLoginNotification: "auth.login.notification",
    AuthLoginSuccess: "auth.login.success",
    AuthLogoutFail: "auth.logout.fail",
    AuthLogoutSuccess: "auth.logout.success",
    AuthSignupFail: "auth.signup.fail",
    AuthSignupSuccess: "auth.signup.success",
    AuthSilentAuthFail: "auth.silent_auth.fail",
    AuthSilentAuthSuccess: "auth.silent_auth.success",
    AuthTokenExchangeFail: "auth.token_exchange.fail",
    AuthTokenExchangeSuccess: "auth.token_exchange.success",
    ManagementFail: "management.fail",
    ManagementSuccess: "management.success",
    ScimEvent: "scim.event",
    SystemNotification: "system.notification",
    UserFail: "user.fail",
    UserNotification: "user.notification",
    UserSuccess: "user.success",
    Actions: "actions",
    Other: "other",
} as const;
