/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface LogStreamPiiConfig {
    log_fields: Management.LogStreamPiiLogFieldsEnum[];
    method?: Management.LogStreamPiiMethodEnum;
    algorithm?: Management.LogStreamPiiAlgorithmEnum;
}
