/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * Configure native social settings
 */
export interface NativeSocialLogin {
    apple?: Management.NativeSocialLoginApple;
    facebook?: Management.NativeSocialLoginFacebook;
    google?: Management.NativeSocialLoginGoogle;
}
