/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface PartialPhoneTemplateContent {
    /** Default phone number to be used as 'from' when sending a phone notification */
    from?: string;
    body?: Management.PhoneTemplateBody;
}
