/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * Defines application access permission for a resource server. Use of this field is subject to the applicable Free Trial terms in Okta’s <a href="https://www.okta.com/legal/"> Master Subscription Agreement.</a>
 */
export interface ResourceServerSubjectTypeAuthorization {
    user?: Management.ResourceServerSubjectTypeAuthorizationUser;
    client?: Management.ResourceServerSubjectTypeAuthorizationClient;
}
