/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { ResourceServerSubjectTypeAuthorizationUserPolicyEnum } from "../types/ResourceServerSubjectTypeAuthorizationUserPolicyEnum.js";

/**
 * Access Permissions for user flows
 */
export interface ResourceServerSubjectTypeAuthorizationUser {
    policy?: ResourceServerSubjectTypeAuthorizationUserPolicyEnum;
    /** Accepts any additional properties */
    [key: string]: any;
}
