// This file was auto-generated by Fern from our API Definition.

import type * as Management from "../index";

export interface SelfServiceProfileBrandingProperties {
    logo_url?: string;
    colors?: Management.SelfServiceProfileBrandingColors;
    /** Accepts any additional properties */
    [key: string]: any;
}
