/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

/**
 * List of attributes to be mapped that will be shown to the user during the SS-SSO flow.
 */
export type SelfServiceProfileUserAttributes = Management.SelfServiceProfileUserAttribute[] | undefined;
