/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { ConnectionsMetadata } from "../types/ConnectionsMetadata.js";
import type { SelfServiceProfileSsoTicketConnectionOptions } from "../types/SelfServiceProfileSsoTicketConnectionOptions.js";

/**
 * If provided, this will create a new connection for the SSO flow with the given configuration
 */
export interface SelfServiceProfileSsoTicketConnectionConfig {
    /** The name of the connection that will be created as a part of the SSO flow. */
    name: string;
    /** Connection name used in the new universal login experience */
    display_name?: string;
    /** <code>true</code> promotes to a domain-level connection so that third-party applications can use it. <code>false</code> does not promote the connection, so only first-party applications with the connection enabled can use it. (Defaults to <code>false</code>.) */
    is_domain_connection?: boolean;
    /** Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by HRD. (Defaults to <code>false</code>.) */
    show_as_button?: boolean;
    metadata?: ConnectionsMetadata;
    options?: SelfServiceProfileSsoTicketConnectionOptions;
}
