/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SessionDate =
    /**
     * The date and time when the session was created */
    | string
    /**
     * The date and time when the session was created */
    | Record<string, unknown>;
