// This file was auto-generated by Fern from our API Definition.

import * as Management from "../index";

export interface SetGuardianFactorsProviderPushNotificationResponseContent {
    provider?: Management.GuardianFactorsProviderPushNotificationProviderDataEnum;
}
