/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface SetGuardianFactorPhoneMessageTypesResponseContent {
    /** The list of phone factors to enable on the tenant. Can include `sms` and `voice`. */
    message_types?: Management.GuardianFactorPhoneFactorMessageTypeEnum[];
}
