// This file was auto-generated by Fern from our API Definition.

import type * as Management from "../index";

export interface UpdateAculResponseContent {
    rendering_mode?: Management.AculRenderingModeEnum;
    /** Context values to make available */
    context_configuration?: string[];
    /** Override Universal Login default head tags */
    default_head_tags_disabled?: boolean | null;
    /** An array of head tags */
    head_tags?: Management.AculHeadTag[];
    filters?: Management.AculFilters | null;
    /** Use page template with ACUL */
    use_page_template?: boolean | null;
    /** Accepts any additional properties */
    [key: string]: any;
}
