/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { BrandingColors } from "../types/BrandingColors.js";
import type { BrandingFont } from "../types/BrandingFont.js";

export interface UpdateBrandingResponseContent {
    colors?: BrandingColors;
    /** URL for the favicon. Must use HTTPS. */
    favicon_url?: string;
    /** URL for the logo. Must use HTTPS. */
    logo_url?: string;
    font?: BrandingFont;
    /** Accepts any additional properties */
    [key: string]: any;
}
