/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type { UpdateEnabledClientConnectionsRequestContentItem } from "../types/UpdateEnabledClientConnectionsRequestContentItem.js";

export type UpdateEnabledClientConnectionsRequestContent = UpdateEnabledClientConnectionsRequestContentItem[];
