/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Management from "../index.js";

export interface UsernameValidation {
    /** Minimum allowed length */
    min_length?: number;
    /** Maximum allowed length */
    max_length?: number;
    allowed_types?: Management.UsernameAllowedTypes;
}
