name: Publish release to npm

inputs:
    node-version:
        required: true
    version:
        required: true
    require-build:
        default: true
    release-directory:
        default: "./"

runs:
    using: composite

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: "yarn"

        - name: Setup yarn
          shell: bash
          run: npm install -g yarn

        - name: Install dependencies
          shell: bash
          run: yarn install --frozen-lockfile

        - name: Build package
          if: inputs.require-build == 'true'
          shell: bash
          run: yarn build

        - name: Validate package
          shell: bash
          run: yarn lint:package

        - name: Publish release to NPM
          shell: bash
          working-directory: ${{ inputs.release-directory }}
          run: |
              publish() {
                npx -y npm@latest publish "$@"
              }
              if [[ "${VERSION}" == *"beta"* ]]; then
                TAG="beta"
              elif [[ "${VERSION}" == *"alpha"* ]]; then
                TAG="alpha"
              else
                TAG="latest"
              fi
              publish --provenance --tag $TAG
          env:
              VERSION: ${{ inputs.version }}
